all:
	(cd context_switch_cost; make)
	(cd system_call_cost; make)
	(cd gettimeofday_precision; make)

clean:
	(cd context_switch_cost; make clean)
	(cd system_call_cost; make clean)
	(cd gettimeofday_precision; make clean)
