all:
	(cd 1; make all)
	(cd 2; make all)
	(cd 3; make all)
	(cd 4; make all)
	(cd 5; make all)
	(cd 6; make all)

clean:
	(cd 1; make clean)
	(cd 2; make clean)
	(cd 3; make clean)
	(cd 4; make clean)
	(cd 5; make clean)
	(cd 6; make clean)
