all:
	(cd 1_2_3; make all)
	(cd 4; make all)
	(cd 5; make all)
	(cd 6; make all)
	(cd 7; make all)
	(cd 8; make all)

clean:
	(cd 1_2_3; make clean)
	(cd 4; make clean)
	(cd 5; make clean)
	(cd 6; make clean)
	(cd 7; make clean)
	(cd 8; make clean)
